[tools]
run-in-roblox = { source = 'rojo-rbx/run-in-roblox', version = '^0.3' }
stylua = { source = 'JohnnyMorganz/stylua', version = '^0.7' }
selene = { source = 'Kampfkarren/selene', version = '^0.11' }
rojo = { source = 'rojo-rbx/rojo', version = '^6.1' }
