name: Build
on: [push, pull_request]

jobs:
  format_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Luau tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Format Luau using StyLua
        run: stylua src test bench bin -c

      - name: Lint Luau using Selene
        run: |
          selene generate-roblox-std
          selene src test bench bin

  unit-test:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build place file
        run: rojo build bin/test.project.json --output bin/test-place.rbxlx

      - name: Run unit tests
        run: run-in-roblox --place bin/test-place.rbxlx --script bin/run-ci-tests.server.lua

  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[release]')
    needs: [format_lint, unit-test]

    steps:
    - uses: actions/checkout@v2

    - name: Install tools
      uses: Roblox/setup-foreman@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build file
      run: rojo build bin/build.project.json --output bin/liter.rbxm

    - name: Get version
      run: |
        VERSION=`grep -Po "(?<=^version = ')([^']+)" rotriever.toml`

        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Get changelog
      run: |
        CHANGELOG_ENTRY=`grep --color=never -m 1 -Po '## \K(\[[0-9\.]+\].+)' CHANGELOG.md`
        DESCRIPTION=`bash bin/extract-changelog.sh $CHANGELOG_ENTRY`

        echo "CHANGELOG_ENTRY=$CHANGELOG_ENTRY" >> $GITHUB_ENV

        echo "CHANGELOG_DESCRIPTION<<EOF" >> $GITHUB_ENV
        echo "$DESCRIPTION" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Upload
      run: rojo upload bin/build.project.json --asset_id 6716155863 --cookie ${{ secrets.ROBLOSECURITY }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.CHANGELOG_ENTRY }}
        tag_name: ${{ env.VERSION }}
        body: ${{ env.CHANGELOG_DESCRIPTION }}
        files: bin/liter.rbxm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
